defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  job:
    chdir: true
#  mode: MULTIRUN
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: ${experiment_name}
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      pl_module.hidden_size: tag(log, int(interval(16, 256)))
      pl_module.lr: tag(log, interval(0.0001, 0.03))

preprocessing:
  salt: '42'
  fold_count_valid: 3
  fold_count_test: 5
  data_path: data/
  folds_path: data/folds/

experiment_name: model_1
tb_save_dir: lightning_logs/${experiment_name}/

mode: valid  # by default

pl_module:
  hidden_size: 64
  lr: 0.001

trainer:
  limit_train_batches: none
  max_epochs: 10
