defaults:
  - data_preprocessing: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: ${experiment_name}
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      pl_module.dropout1: choice(0, 0.1, 0.2, 0.3)
      pl_module.batch_norm1: choice(false, true)
      pl_module.hidden_size1: tag(log, int(interval(16, 256)))
      pl_module.lr: tag(log, interval(0.0001, 0.03))
      pl_module.lr_gamma: interval(0.4, 1.0)

experiment_name: one_layer_head
tb_save_dir: lightning_logs/${experiment_name}/

mode: ???

pl_module:
  num_layers: 1
  dropout1: 0
  batch_norm1: true
  relu1: false
  hidden_size1: 64
  lr: 0.001
  lr_gamma: 0.9

validation_rate: 0.1

trainer:
  limit_train_batches: 100
  max_epochs: 5
