name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip "setuptools<=74.0.0"
        pip install "pipenv<24.1.0"
        pipenv run python -m pip install "pip==24.0" "setuptools<=74.0.0"
        pipenv run pip --version
        pipenv sync --dev
    - name: Test with pytest
      run: |
        pipenv run coverage run
        pipenv run coverage report
    - name: Build a source tarball
      if: startsWith(github.ref, 'refs/tags')
      run: |
        pipenv run python setup.py sdist
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
