name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        python-version: [ 3.8 ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev
        pip install pytest pytest-cov

    - name: Upgrade pandas-dask, torch
      run: |
        pip install --upgrade pandas "dask[complete]"
        pip install torch==2.1.0+cu121 torchvision==0.16.0+cu121 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu121

    - name: Test with pytest
      run: |
        pipenv run coverage run
#        pytest --cov=ptls -s ptls_tests
#        pipenv run coverage report

#    TODO: add this later
#    - name: Codecov-coverage
#      uses: codecov/codecov-action@v4
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}